# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
rssFullContent = true

[footer]
since = 2019
customText = "正是那不可預見的益使我珍視。"

[dateFormat]
published = "Mon, Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "⭐"
subtitle = "As boiled as the script."

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = true
local = true
src = "img/opengraph.jpg"

[colorScheme]
toggle = false
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true
